#ifndef _IO_H
#define _IO_H

/* 
	This file is normally autogenerated by the AVR compiler, this doesnt work for testing so we need to 
	manually pull in necessary header files here to allow for compilation.
*/
#include "twim_110.h"
#include "gpio.h"
#endif